### ISSUE TITLE
Questions abount the pretrained model

### ISSUE THREAD

**Issue by yfzhang114** [erobic/occam-nets-v1#1]
Hey, excellent work.
  Can you share the OCCAMNet checkpoint that is pretrained on the imagenet?

**Comment by erobic** [comment]
Hi,

Thank you for your interest in OccamNet.
I recently trained OccamNetv1 on 100 classes of ImageNet with this codebase and am sending the [checkpoint](https://drive.google.com/file/d/1if0HC_24TWhO1cXyXZ-0ad8eND6VDXD0/view?usp=sharing) + script to test it.

```
CUDA_VISIBLE_DEVICES=${GPU} python main.py \
model.name=occam_resnet18 \
trainer=occam_trainer_image_net \
trainer.precision=${precision} \
dataset=${dataset} \
dataset.batch_size=128 \
optimizer=${optim} \
expt_suffix=test_prec_${precision}_thresh_0.2 \
'checkpoint_path="/path/occam_net_v1_image_net_100.ckpt"' \
task.name='test' \
data_sub_split='val'
```

Note that the numbers provided in the paper are also for 100 classes and I am looking to improve the design before we scale it up to full set.
Thank you!
